name: Build and deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: eshopserver
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  ARTIFACT_NAME: "dotnet-app.zip"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore ./eShopSolution.sln

      - name: Build
        run: dotnet build ./eShopSolution.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./eShopSolution.sln --configuration Release --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Compress publish directory
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          zip -r ../${{ env.ARTIFACT_NAME }} *

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-app
          path: ${{ env.ARTIFACT_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: dotnet-app

      - name: Unzip artifact
        run: |
          unzip dotnet-app.zip -d ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
