name: Build and deploy ASP.Net Core apps to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_WEBAPP_NAME: ForTestMain
      ARTIFACTS_PATH: ./publish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Restore dependencies
        run: dotnet restore ./eShopSolution.sln

      - name: Build projects
        run: dotnet build ./eShopSolution.sln --configuration Release --no-restore

      - name: Publish Admin App
        run: dotnet publish ./eShopSolution.AdminApp/eShopSolution.AdminApp.csproj --configuration Release --output ${{ env.ARTIFACTS_PATH }}/eShopSolution.AdminApp

      - name: Publish Customer App
        run: dotnet publish ./eShopSolution.WebApp/eShopSolution.WebApp.csproj --configuration Release --output ${{ env.ARTIFACTS_PATH }}/eShopSolution.WebApp

      - name: Publish API
        run: dotnet publish ./eShopSolution.BackendApi/eShopSolution.BackendApi.csproj --configuration Release --output ${{ env.ARTIFACTS_PATH }}/eShopSolution.BackendApi

      - name: Deploy Admin App to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.ARTIFACTS_PATH }}/AdminApp

      - name: Deploy Customer App to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.ARTIFACTS_PATH }}/WebApp

      - name: Deploy API to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.ARTIFACTS_PATH }}/BackendApi
